stages:          # List of stages for jobs, and their order of execution
  - build
  #- test
  #- deploy

build_job:
  stage: build
  script:
    - 'dotnet build geometry4Sharp_netstandard.csproj -c Release'
    - 'dotnet pack geometry4Sharp_netstandard.csproj -c Release'
  artifacts:
      paths:
        - bin/

